---
title: "The Effect of Asset Purchase Programmes on Asset Prices and Inequality"
author: "Thomas Schiller"
date: "12/12/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

In response to the Global Financial Crisis (GFC), on October 8<sup>th</sup> 2008, the Federal Researve, along with five other central banks, collectively reduced interest rates. The Federal Open Market Committee (FOMC) lowered its federal funds rate target to 1.5 percent. Then, on December 16<sup>th</sup> 2008, the FOMC cut its target rate effectively to zero (a target rate between 0 and 0.25 percent). 

In addition, the Federal Reserve (along with other central banks) launched a large-scale asset purchase (LSAP) programme on November 25<supth</sup> (QE1) with the intention of providing additional monetary stimulus to the economy (Hesse, Hofmann and Weber 2018). LSAP programmes, along with other _balance sheet policies_, are one of the two ways in which central banks implement monetary policy (the other being _interest rate policy_)  (Borio and Zabai 2016). 

-- Plot of Fed balance sheet --   

This paper analyses the effects of the Federal Reserve's LSAP programmes. Specifically, the effects on asset prices and wealth inequality are analysed. This is done using an SVAR approach to compute the effects of LSAP on asset prices, among other variables. The effects will then be used to compute a measure of the effect on inequality, following the approach of Domanski, Scatigna and Zabai (2016).    


## References 

Borio, C. Zabai A.(2016):  Unconventional monetary policies:  are-appraisal (No.  570).  BIS Working Papers

Domanski, D., Scatigna, M.,   Zabai, A. (2016).  Wealth inequalityand monetary policy.  BIS Quarterly Review March

Hesse, H., Hofmann, B.,   Weber, J. (2018).  The macroeconomiceffects of asset purchases revisited (No.  680).  BIS Working Papers
